### PR TITLE
Optimised wsclean predict

### PR DESCRIPTION
**Pull request by sjperkins**
- [x] Tests added / passed

  ```bash
  $ py.test --flake8 -v -s .
  ```

  If the flake8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8`
  to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8
  $ autopep8 -r -i .
  $ flake8 .
  ```

### CODE REVIEW

**Comment by paoloserra** [comment]
Below I show 4 regions of a continuum image made from a test .MS with WSclean (left panels)  and the line spectrum extracted at the position of the green open circle (right panels). The red line shows the spectrum before continuum subtraction. The white line shows the spectrum after continuum subtraction. The continuum is subtracted by subtracting the MODEL_DATA column written by crystalball from the CORRECTED_DATA column of the .MS.

The plots show that the new, optimised code is doing the right thing: the correct continuum flux density is subtracted at the correct RA,Dec.

We can therefore proceed with measuring the memory requirements and speed of the new code compared to crystalball 0.2.4.

**Comment by sjperkins** [comment]
Note that I've reduced the default memory requirements from 0.1 to 0.5 as
the new code seems to be able to exercise cores with smaller chunks.

Additionally, the source chunk size could probably be increased further
with minimal impact at memory

**Comment by paoloserra** [comment]
Very happy with this version. I'm OK with releasing the new version of codex-africanus, and then  a crystalball 0.2.5.

```
2020-04-02 19:43:32 | INFO     | budget:get_budget | -------------------------------------------
2020-04-02 19:43:32 | INFO     | budget:get_budget | system RAM = 251.78 GB
2020-04-02 19:43:32 | INFO     | budget:get_budget | nr of logical CPUs = 42
2020-04-02 19:43:32 | INFO     | budget:get_budget | nr sources = 68796
2020-04-02 19:43:32 | INFO     | budget:get_budget | nr rows    = 5744370
2020-04-02 19:43:32 | INFO     | budget:get_budget | nr chans   = 766
2020-04-02 19:43:32 | INFO     | budget:get_budget | nr corrs   = 2
2020-04-02 19:43:32 | INFO     | budget:get_budget | sources per chunk = 840 (auto settings)
2020-04-02 19:43:32 | INFO     | budget:get_budget | rows per chunk    = 84030 (auto settings)
2020-04-02 19:43:32 | INFO     | budget:get_budget | expected memory usage = 50.35 GB
```
sj_3

**Comment by paoloserra** [comment]
Thank you @sjperkins , great improvements!!!

**Pull request merged**
