### PR TITLE
Python3 upgrade

### PR DESCRIPTION
**Pull request by sjperkins**

### CODE REVIEW

**Comment by sjperkins** [comment]
Work in Progress, please don't merge yet.

**Comment by paoloserra** [comment]
happy for this to be merged now?

**Comment by sjperkins** [comment]
@paoloserra I've tested that it runs through on an MS + source model but @SpheMakh is just going to test that it does the right thing. I'm not expecting breakages but it never hurts to be sure.

**Comment by sjperkins** [comment]
This is ready to merge.

**Pull request merged**
