### PR TITLE
Upgrade to dask-ms 0.2.3

### PR DESCRIPTION
**Pull request by sjperkins**
- [x]  Tests added / passed

  ```bash
  $ py.test --flake8 -v -s .
  ```

  If the flake8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8`
  to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8
  $ autopep8 -r -i .
  $ flake8 .
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
Upgrade to dask-ms 0.2.3 to take advantage of https://github.com/ska-sa/dask-ms/pull/75

**Comment by sjperkins** [comment]
@paoloserra @SpheMakh Would someone with write access to the repository please review this PR? It solves the OutOfMemory issues. 

@PeterKamphuis tested this branch out in https://github.com/ska-sa/meerkathi/issues/723#issuecomment-567431537

**Comment by KshitijT** [comment]
> @paoloserra @SpheMakh Would someone with write access to the repository please review this PR? It solves the OutOfMemory issues.
> 
> @PeterKamphuis tested this branch out in [ska-sa/meerkathi#723 (comment)](https://github.com/ska-sa/meerkathi/issues/723#issuecomment-567431537)

Seconded, right now we need to install this branch separately and run crystalball out of the pipeline and then resume it again, which is all very cumbersome.

**Comment by gigjozsa** [comment]
> > @paoloserra @SpheMakh Would someone with write access to the repository please review this PR? It solves the OutOfMemory issues.
> > @PeterKamphuis tested this branch out in [ska-sa/meerkathi#723 (comment)](https://github.com/ska-sa/meerkathi/issues/723#issuecomment-567431537)
> 
> Seconded, right now we need to install this branch separately and run crystalball out of the pipeline and then resume it again, which is all very cumbersome.

Thirded...

**Comment by PeterKamphuis** [comment]
> > > @paoloserra @SpheMakh Would someone with write access to the repository please review this PR? It solves the OutOfMemory issues.
> > > @PeterKamphuis tested this branch out in [ska-sa/meerkathi#723 (comment)](https://github.com/ska-sa/meerkathi/issues/723#issuecomment-567431537)
> > 
> > 
> > Seconded, right now we need to install this branch separately and run crystalball out of the pipeline and then resume it again, which is all very cumbersome.
> 
> Thirded...

Fourthet

**Comment by gigjozsa** [comment]
@paoloserra needs to create a release to make it usable for Stimela/MeerKATHI.

**Comment by gigjozsa** [comment]
@SpheMakh can do this as well.

**Comment by gigjozsa** [comment]
@SpheMakh did so just now. @Athanaseus can now include this in Stimela.

**Pull request merged**
