### PR TITLE
Use EstimatingProgressBar

### PR DESCRIPTION
**Pull request by sjperkins**
- [ ] Tests added / passed

  ```bash
  $ py.test --flake8 -v -s .
  ```

  If the flake8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8`
  to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8
  $ autopep8 -r -i .
  $ flake8 .
  ```

### CODE REVIEW

**Comment by paoloserra** [comment]
Testing now. It's jumped to 17% after a few seconds, which seems unlikely.

`[######                                  ] | 17% Completed |  3.4s | ~ 7.8s`

I guess the last number is  the estimated remaining time. During the first few minutes of execution that number increases steadily. I guess that after a while it will converge to something closer to the correct value.

`[######                                  ] | 17% Completed |  5min 33.5s | ~12min 43.7s`

Will keep posting  updates as it goes -- it'll be a long  job:

```
2020-04-03 19:26:16 | INFO     | budget:get_budget | -------------------------------------------
2020-04-03 19:26:16 | INFO     | budget:get_budget | system RAM = 251.78 GB
2020-04-03 19:26:16 | INFO     | budget:get_budget | nr of logical CPUs = 42
2020-04-03 19:26:16 | INFO     | budget:get_budget | nr sources = 68796
2020-04-03 19:26:16 | INFO     | budget:get_budget | nr rows    = 5744370
2020-04-03 19:26:16 | INFO     | budget:get_budget | nr chans   = 766
2020-04-03 19:26:16 | INFO     | budget:get_budget | nr corrs   = 2
2020-04-03 19:26:16 | INFO     | budget:get_budget | sources per chunk = 1680 (auto settings)
2020-04-03 19:26:16 | INFO     | budget:get_budget | rows per chunk    = 168061 (auto settings)
2020-04-03 19:26:16 | INFO     | budget:get_budget | expected memory usage = 100.71 GB
2020-04-03 19:26:17 | INFO     | crystalball:_predict | Field 0 DDID 0
2020-04-03 19:26:17 | INFO     | crystalball:_predict | -------------------------------------------
2020-04-03 19:26:17 | INFO     | crystalball:_predict | Nr sources        = 68796
2020-04-03 19:26:17 | INFO     | crystalball:_predict | -------------------------------------------
2020-04-03 19:26:17 | INFO     | crystalball:_predict | Correlations      = [2]
2020-04-03 19:26:17 | INFO     | crystalball:_predict | frequency.shape   = (766,)
2020-04-03 19:26:17 | INFO     | crystalball:_predict | visibility.shape  = (5744370, 766, 2)
```

**Comment by sjperkins** [comment]
Those initial predict chunks are going to take some time because the dimension sizes are so big. Once that is done, it should be able to provide a better estimate of the total time.

Also note that going forward, far smaller fractions should be able to exercise the cores.

**Comment by paoloserra** [comment]
Here's a few snapshots of the progress bar. It seems to have converged on a total execution time of ~125 h after ~10% of that time had passed. If confirmed (I'll keep this running) I think this would be totally acceptable. In that case, we could print a warning explaining how to interpret the  progress bar --  just above the progress bar.

```
[######                      ] | 17% Completed | 3.4s             | ~ 7.8s
[######                      ] | 17% Completed | 5min 33.5s       | ~12min 43.7s
[######                      ] | 17% Completed |  1hr 57min 11.2s | ~ 4hr 28min 20.8s
[########                    ] | 21% Completed |  6hr  0min 35.8s | ~116hr 33min 56.5
[#########                   ] | 24% Completed | 10hr 44min 31.2s | ~116hr 46min  9.7ss
[##########                  ] | 26% Completed | 12hr 11min 20.3s | ~104hr  6min 38.3s
[##########                  ] | 26% Completed | 13hr  5min 27.8s | ~110hr 29min 59.3s
[###########                 ] | 28% Completed | 14hr 54min 18.1s | ~108hr 33min 37.3s
[###########                 ] | 29% Completed | 16hr  0min  1.8s | ~107hr 17min 22.1s

```

**Comment by paoloserra** [comment]
New update. The total execution time predicted by the progress bar has not changed dramatically. It's still within ~20% of what it was initially (that  is, after ~10% of the expected total time had passed). I think that's not too bad. We'll see whether it stays like that.

```
[######                      ] | 17% Completed | 3.4s             | ~ 7.8s
[######                      ] | 17% Completed | 5min 33.5s       | ~12min 43.7s
[######                      ] | 17% Completed |  1hr 57min 11.2s | ~ 4hr 28min 20.8s
[########                    ] | 21% Completed |  6hr  0min 35.8s | ~116hr 33min 56.5s
[#########                   ] | 24% Completed | 10hr 44min 31.2s | ~116hr 46min  9.7s
[##########                  ] | 26% Completed | 12hr 11min 20.3s | ~104hr  6min 38.3s
[##########                  ] | 26% Completed | 13hr  5min 27.8s | ~110hr 29min 59.3s
[###########                 ] | 28% Completed | 14hr 54min 18.1s | ~108hr 33min 37.3s
[###########                 ] | 29% Completed | 16hr  0min  1.8s | ~107hr 17min 22.1s
[############                ] | 31% Completed | 19hr  2min 12.2s | ~106hr 42min 25.2s
[#############               ] | 34% Completed | 22hr 43min 10.6s | ~106hr 11min 38.4s
[##############              ] | 37% Completed | 26hr  9min 35.4s | ~106hr  2min 23.2s
[###############             ] | 39% Completed | 27hr 45min 49.3s | ~103hr 12min 43.8s
[##################          ] | 45% Completed | 35hr 25min 57.9s | ~103hr 45min 50.2s
[##################          ] | 47% Completed | 37hr 58min 49.8s | ~103hr 36min 49.3s
[###################         ] | 49% Completed | 41hr  5min 29.1s | ~102hr 43min 42.1s
[####################        ] | 52% Completed | 43hr 49min  1.8s | ~102hr 24min 10.9
[######################      ] | 57% Completed | 49hr 58min 52.1s | ~102hr 18min 51.9s
```

**Comment by paoloserra** [comment]
@sjperkins can you confirm that the last number on each row is the estimated total time, not the estimated remaining time? If so -- looking good!

(It might  make more sense to stop at "~hh mm".)

```
[######                                  ] | 17% Completed | 3.4s             | ~ 7.8s
[######                                  ] | 17% Completed | 5min 33.5s       | ~12min 43.7s
[######                                  ] | 17% Completed |  1hr 57min 11.2s | ~ 4hr 28min 20.8s
[########                                ] | 21% Completed |  6hr  0min 35.8s | ~116hr 33min 56.5s
[#########                               ] | 24% Completed | 10hr 44min 31.2s | ~116hr 46min  9.7s
[##########                              ] | 26% Completed | 12hr 11min 20.3s | ~104hr  6min 38.3s
[##########                              ] | 26% Completed | 13hr  5min 27.8s | ~110hr 29min 59.3s
[###########                             ] | 28% Completed | 14hr 54min 18.1s | ~108hr 33min 37.3s
[###########                             ] | 29% Completed | 16hr  0min  1.8s | ~107hr 17min 22.1s
[############                            ] | 31% Completed | 19hr  2min 12.2s | ~106hr 42min 25.2s
[#############                           ] | 34% Completed | 22hr 43min 10.6s | ~106hr 11min 38.4s
[##############                          ] | 37% Completed | 26hr  9min 35.4s | ~106hr  2min 23.2s
[###############                         ] | 39% Completed | 27hr 45min 49.3s | ~103hr 12min 43.8s
[##################                      ] | 45% Completed | 35hr 25min 57.9s | ~103hr 45min 50.2s
[##################                      ] | 47% Completed | 37hr 58min 49.8s | ~103hr 36min 49.3s
[###################                     ] | 49% Completed | 41hr  5min 29.1s | ~102hr 43min 42.1s
[####################                    ] | 52% Completed | 43hr 49min  1.8s | ~102hr 24min 10.9
[######################                  ] | 57% Completed | 49hr 58min 52.1s | ~102hr 18min 51.9s
[#########################               ] | 64% Completed | 58hr 54min 19.6s | ~101hr 21min 10.4s
[###########################             ] | 68% Completed | 62hr 59min 27.4s | ~100hr 32min 40.1s
[############################            ] | 71% Completed | 66hr  6min 14.5s | ~100hr 41min 49.4s
[#############################           ] | 73% Completed | 69hr 12min 44.3s | ~100hr 43min 46.5s
[#############################           ] | 74% Completed | 70hr 44min  1.0s | ~101hr 30min  6.8s
[##############################          ] | 77% Completed | 73hr 30min  4.0s | ~101hr  7min 28.8s

```

**Comment by sjperkins** [comment]
> @sjperkins can you confirm that the last number on each row is the estimated total time, not the estimated remaining time? If so -- looking good!

Yes it is.

I going to quickly see if I can improve the estimation process somewhat. Currently, tasks are binned fairly coarsely. Increasing the granularity may improve things.

**Comment by paoloserra** [comment]
> I going to quickly see if I can improve the estimation process somewhat. Currently, tasks are binned fairly coarsely.

Sounds good. How would you feel about a release today or tomorrow?

**Comment by sjperkins** [comment]
> It might make more sense to stop at "~hh mm"

I'll work this into the bar too

> Sounds good. How would you feel about a release today or tomorrow?

I think tomorrow is more achievable as I've got quite a few meetings today.

**Comment by sjperkins** [comment]
I've added the bar into codex. You may want to give it a try overnight? Otherwise I'm happy with the bar as it stands. It's less busy than the default dask progress bar, displaying only the 2 most signifcant time units and updating every second.

This may give an idea of what it looks like:

```bash
$ crystalball ~/data/1527016443_sdp_l0.full_1284.full_pol.ms -sm ~/data/edb_2-sources.txt 
2020-04-07 14:04:11 | INFO     | crystalball:_predict | Crystalball version 0.2.4
2020-04-07 14:04:11 | INFO     | wsclean:import_from_wsclean | /home/sperkins/data/edb_2-sources.txt contains 4603 components
2020-04-07 14:04:11 | INFO     | wsclean:import_from_wsclean | Total flux of 4603 selected components is 2.936560 Jy
Successful read/write open of default-locked table /home/sperkins/data/1527016443_sdp_l0.full_1284.full_pol.ms: 25 columns, 63936 rows
2020-04-07 14:04:11 | INFO     | budget:get_budget | -------------------------------------------
2020-04-07 14:04:11 | INFO     | budget:get_budget | system RAM = 15.47 GB
2020-04-07 14:04:11 | INFO     | budget:get_budget | nr of logical CPUs = 8
2020-04-07 14:04:11 | INFO     | budget:get_budget | nr sources = 4603
2020-04-07 14:04:11 | INFO     | budget:get_budget | nr rows    = 63936
2020-04-07 14:04:11 | INFO     | budget:get_budget | nr chans   = 4096
2020-04-07 14:04:11 | INFO     | budget:get_budget | nr corrs   = 4
2020-04-07 14:04:11 | INFO     | budget:get_budget | sources per chunk = 12 (auto settings)
2020-04-07 14:04:11 | INFO     | budget:get_budget | rows per chunk    = 1267 (auto settings)
2020-04-07 14:04:11 | INFO     | budget:get_budget | expected memory usage = 1.55 GB
2020-04-07 14:04:11 | INFO     | crystalball:_predict | Field 0 DDID 0
2020-04-07 14:04:11 | INFO     | crystalball:_predict | -------------------------------------------
2020-04-07 14:04:11 | INFO     | crystalball:_predict | Nr sources        = 4603
2020-04-07 14:04:11 | INFO     | crystalball:_predict | -------------------------------------------
2020-04-07 14:04:11 | INFO     | crystalball:_predict | Correlations      = [4]
2020-04-07 14:04:11 | INFO     | crystalball:_predict | frequency.shape   = (4096,)
2020-04-07 14:04:11 | INFO     | crystalball:_predict | visibility.shape  = (39294, 4096, 4)
2020-04-07 14:04:11 | INFO     | crystalball:_predict | Field 1 DDID 0
2020-04-07 14:04:11 | INFO     | crystalball:_predict | -------------------------------------------
2020-04-07 14:04:11 | INFO     | crystalball:_predict | Nr sources        = 4603
2020-04-07 14:04:11 | INFO     | crystalball:_predict | -------------------------------------------
2020-04-07 14:04:11 | INFO     | crystalball:_predict | Correlations      = [4]
2020-04-07 14:04:11 | INFO     | crystalball:_predict | frequency.shape   = (4096,)
2020-04-07 14:04:11 | INFO     | crystalball:_predict | visibility.shape  = (24642, 4096, 4)
[#                                         ] | 3% Complete (Estimate) |  2m32s / ~ 1h10m
```

**Comment by paoloserra** [comment]
Cool. Only one comment. There is a lot of repetition between `budget:get_budget` and `crystalball:_predict`. Can we remove the redundant bits? Also, could you explain the two sections of `crystalball:_predict`? I don't think I had seen that splitting into fields before. I'm a little confused since the input WSclean model is single-field.

**Comment by sjperkins** [comment]
> There is a lot of repetition between budget:get_budget and crystalball:_predict. Can we remove the redundant bits?

I don't see the redundancy. Could you provide links to the specific code?

> Also, could you explain the two sections of crystalball:_predict? I don't think I had seen that splitting into fields before. I'm a little confused since the input WSclean model is single-field.

**xds_from_ms** partitions the MS data into separate datasets by FIELD_ID and DATA_DESC_ID, by default. Thus, if there is only one FIELD_ID (and DATA_DESC_ID) in the MS, there'll be one dataset so this shouldn't matter.

Each field has a different phase direction (PHASE_DIR). This is why xds_from_ms partitions on FIELD.

**Comment by paoloserra** [comment]
> > There is a lot of repetition between budget:get_budget and crystalball:_predict. Can we remove the redundant bits?
> 
> I don't see the redundancy. Could you provide links to the specific code?

the number of sources, channels, corrs is repeated in both `budget:get_budget` and `crystalball:_predict`

**Comment by sjperkins** [comment]
> the number of sources, channels, corrs is repeated in both budget:get_budget and crystalball:_predict

Ah, in the logging?

**Comment by sjperkins** [comment]
The reason for the duplication of logging, at least with FIELD_ID and DATA_DESC_ID, is that the number of channels and correlations might differ with each DATA_DESC_ID and the PHASE_DIR will differ per FIELD_ID.

I guess I could log per DATA_DESC_ID.

**Comment by paoloserra** [comment]
No big deal -- but I'm still confused about the fields. We only support a single input WSclean table, and that will be for a single field since it comes from imaging. So I am a little worried about even discussing how we log info for multiple fields.

**Comment by sjperkins** [comment]
There's a switch that the user can use to select specific fields to predict. I don't know of an automated way to connect the WSClean sky model to a specific FIELD.

**Comment by paoloserra** [comment]
There isn't one, indeed. Let me put it a different way. Predicting MODEL_DATA for multiple fields of an .MS from the same WSclean table is going to be wrong in all cases I can think of. We just shouldn't be doing it. If an .MS has multiple fields we should stop and request that the user tells which field they want to work on. A corollary of that is that the per-field section of the logging should not be there.

**Comment by sjperkins** [comment]
> There isn't one, indeed. Let me put it a different way. Predicting MODEL_DATA for multiple fields of an .MS from the same WSclean table is going to be wrong in all cases I can think of. We just shouldn't be doing it. If an .MS has multiple fields we should stop and request that the user tells which field they want to work on. A corollary of that is that the per-field section of the logging should not be there.

OK, this probably wasn't picked up in https://github.com/paoloserra/crystalball/pull/30. I'll limit the predict to a single field.

**Comment by paoloserra** [comment]
Yes, my bad, I should have noticed earlier. I now realised this thanks to the logging :)

**Comment by sjperkins** [comment]
@paoloserra Updated, let me know if you're happy.

Then I'll do a codex release, we can merge this PR, then do the crystalball release.

**Comment by paoloserra** [comment]
Thanks @sjperkins , will do!

**Comment by sjperkins** [comment]
> Thanks @sjperkins , will do!

Fixed some more things, https://github.com/paoloserra/crystalball/pull/36/commits/c3edae832f2afe2bff97372b22b0d343894d9219 was a bit glaring

**Comment by paoloserra** [comment]
@sjperkins this isn't working. as well as it did in my previous test (see above for a comparison; it's the same run, so it's going to take ~100 h)

```
[####################################      ] | 87% Complete (Estimate) |     4s / ~    5s
[####################################      ] | 87% Complete (Estimate) |  1m17s / ~ 1m28s
[####################################      ] | 87% Complete (Estimate) |  3m48s / ~ 4m21s
[####################################      ] | 87% Complete (Estimate) | 21m17s / ~24m17s
[####################################      ] | 87% Complete (Estimate) |  1h13m / ~ 1h24m
```

**Comment by sjperkins** [comment]
> @sjperkins this isn't working as well as it did in my previous test (see above for a comparison; it's the same run, so it's going to take ~100 h)
> 
> ```
> [####################################      ] | 87% Complete (Estimate) |     4s / ~    5s
> [####################################      ] | 87% Complete (Estimate) |  1m17s / ~ 1m28s
> [####################################      ] | 87% Complete (Estimate) |  3m48s / ~ 4m21s
> [####################################      ] | 87% Complete (Estimate) | 21m17s / ~24m17s
> [####################################      ] | 87% Complete (Estimate) |  1h13m / ~ 1h24m
> ```

It's now calculating the bar based on the last ratio (100 * elapsed_time / estimated_time) instead of (100 * completed_tasks / total_tasks). Let it run for a bit longer to see if if estimate_time jumps so that things look better?

The initial 87% guess is not ideal, but then neither is the task estimate. What is your preference?

**Comment by paoloserra** [comment]
> Let it run for a bit longer to see if if estimate_time jumps so that things look better?

Yes, I'll keep it going. In the previous test things seem to have converged after ~10 h. I will continue updating the post above.

**Comment by paoloserra** [comment]
OK, it seems to have recovered but I'm wondering whether there's a small bug somewhere: look at the expected total time in the last 4 entries.

Other than that, this is fine with me.

I don't have a strong opinion about whether this is better than the bar based on the number of tasks. Would you mind picking whatever you think is best?

```
[####################################      ] | 87% Complete (Estimate) |     4s / ~    5s
[####################################      ] | 87% Complete (Estimate) |  1m17s / ~ 1m28s
[####################################      ] | 87% Complete (Estimate) |  3m48s / ~ 4m21s
[####################################      ] | 87% Complete (Estimate) | 21m17s / ~24m17s
[####################################      ] | 87% Complete (Estimate) |  1h13m / ~ 1h24m
[####################################      ] | 87% Complete (Estimate) |  2h17m / ~ 2h37m
[                                          ] | 2% Complete (Estimate) |  3h 5m / ~ 5d 5h
[#                                         ] | 2% Complete (Estimate) |  3h19m / ~ 4d 4h
[#                                         ] | 2% Complete (Estimate) |  4h 2m / ~ 5d 5h
[#                                         ] | 2% Complete (Estimate) |  4h29m / ~ 6d 6h
```

**Comment by sjperkins** [comment]
OK I've got a fix for the day == hours output in https://github.com/ska-sa/codex-africanus/pull/183.

> 

I don't have a strong opinion about whether this is better than the bar based on the number of tasks. Would you mind picking whatever you think is best?

I think I'll interpolate between tasks and estimated time using a sigmoid function.

**Comment by paoloserra** [comment]
> I think I'll interpolate between tasks and estimated time using a sigmoid function.

seriously?!

**Comment by paoloserra** [comment]
@sjperkins I've tested this again, looks good. OK to merge and release?

**Comment by sjperkins** [comment]
OK by me. Thanks for your all your help with the testing.

**Comment by sjperkins** [comment]
> > I think I'll interpolate between tasks and estimated time using a sigmoid function.
> 
> seriously?!

I thought I posted earlier, but I see I didn't press the button.

I'm still using elapsed / estimated in the bar, but for the first 10 seconds the user is informed that the estimate will improve over time.

**Pull request merged**
