### PR TITLE
Upgrade to dask-ms==0.2.5, codex-africanus==0.2.5

### PR DESCRIPTION
**Pull request by sjperkins**
- [x] Tests added / passed

  ```bash
  $ py.test --flake8 -v -s .
  ```

  If the flake8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8`
  to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8
  $ autopep8 -r -i .
  $ flake8 .
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
Codex PR: https://github.com/ska-sa/codex-africanus/pull/206

**Comment by paoloserra** [comment]
This works for me (with codex PR 206).

Below I show spectra before any continuum subtraction (white), after subtraction of a delta-only model (green), and after the old and the new subtraction of a same multi-scale model (red and orange, respectively).

The first plot is at a position where a delta component dominates. In this case both old (red) and new (orange) Gaussian model subtraction  give identical results as the subtraction of a delta-only model (green).

Screen Shot 2020-07-01 at 00 24 53

The second plot is at a position where a Gaussian component dominates. In this case the new Gaussian model subtraction (orange) is better and agrees with the delta-only model subtraction (green). The old Gaussian model subtraction (red) leaves a significant amount of continuum flux behind.

Screen Shot 2020-07-01 at 00 25 23

So I'm happy with these changes. @sjperkins let me know whether this is all finalised on your side and can be merged as is.

**Comment by sjperkins** [comment]
@paoloserra I've released codex-africanus 0.2.5 https://pypi.org/project/codex-africanus/ with the fix and updated this branch to depend on that version.

I therefore think this branch is ready for merge.

**Comment by sjperkins** [comment]
Thanks for testing this fix!

**Pull request merged**
